### Create Goals

POST http://localhost:3333/goals
content-type: application/json

{
  "title": "Alimentação saudavel",
  "desiredWeeklyFrequency": 5
}

### Get week pending-goals
GET http://localhost:3333/pending-goals

### Create goals completions
POST http://localhost:3333/completions
content-type: application/json

{
  "goalId": "ku5utmffo8jy6nzi63kl7h9s"
}

### Get week summary
GET http://localhost:3333/summary

### Create Folder
POST http://localhost:3333/folder
content-type: application/json

{
  "name": "pasta 2",
  "userId": "n6u53804o7fjhg08tit8csc1"
}

### Get Folder
GET http://localhost:3333/folder/summary

### Get profile 
GET http://localhost:3333/profile

### Authenticate
POST http://localhost:3333/auth/authenticate
content-type: application/json

{
  "email": "test2@gmail.com",
  "password": "12345678"
}

### Create a new user

POST http://localhost:3333/user
content-type: application/json

{
  "email": "test3@gmail.com",
  "name": "teste3",
  "password": "12345678",
  "avatarUrl": "https://foto3.png"
}

### Create a new note
POST http://localhost:3333/note
content-type: application/json

{
  "title": "Nota teste",
  "userId": "n6u53804o7fjhg08tit8csc1",
  "folder_id": "tncao1vtw5xwz1zx4x4noqlt",
  "tags": "nota 2",
  "content": "SEI LÁ, JA PERDI AS CONTAS"
}

### Get notes 
GET http://localhost:3333/notes/summary

### Get note with tags
POST http://localhost:3333/notes/find
content-type: application/json

{
  "tags": "nota 3"
}

### Get notes with Folder
GET http://localhost:3333/notes/summary/?userId=n6u53804o7fjhg08tit8csc1&folder_id=tncao1vtw5xwz1zx4x4noqlt

### Find note by id
GET http://localhost:3333/notes/?id=es1log90f348n7ie877apjbv

### Updated note
PUT http://localhost:3333/notes/?id=es1log90f348n7ie877apjbv
content-type: application/json

{
  "title": "Att da nota nova 3",
  "content": "novo contetudo"
}

### Delete note 
DELETE http://localhost:3333/notes/delete/?id=es1log90f348n7ie877apjbv

### Create a new Task
POST http://localhost:3333/task
content-type: application/json  

{
  "title": "Estudar javascript",
  "userId": "n6u53804o7fjhg08tit8csc1",
  "content": "Quero estudar javascrip no dia 12",
  "is_completed": false
}

### Get tasks
GET http://localhost:3333/task/summary

### Updated task

PUT http://localhost:3333/task/update/?id=m37o90wfo2sm60vrx01rzo4o
content-type: application/json

{
  "title": "Att da tarefa",
  "content": "novo contetudo da tarefa",
  "is_completed": true
}

### Delete task

DELETE http://localhost:3333/task/delete/?id=m37o90wfo2sm60vrx01rzo4o

